
REVOKE ALL PRIVILEGES ON SCHEMA catalog FROM catalog_manager;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA catalog FROM catalog_manager;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA catalog FROM catalog_manager;


REVOKE ALL PRIVILEGES ON SCHEMA sales FROM sales_manager;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA sales FROM sales_manager;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA sales FROM sales_manager;

REVOKE USAGE ON SCHEMA catalog FROM sales_manager;
REVOKE SELECT ON ALL TABLES IN SCHEMA catalog FROM sales_manager;


REVOKE USAGE ON SCHEMA catalog FROM PUBLIC;
REVOKE SELECT ON ALL TABLES IN SCHEMA catalog FROM PUBLIC;