

GRANT USAGE ON SCHEMA catalog TO catalog_manager;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA catalog TO catalog_manager;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA catalog TO catalog_manager;
GRANT CREATE ON SCHEMA catalog TO catalog_manager;


ALTER DEFAULT PRIVILEGES FOR ROLE catalog_manager IN SCHEMA catalog
    GRANT ALL PRIVILEGES ON TABLES TO catalog_manager;

ALTER DEFAULT PRIVILEGES FOR ROLE catalog_manager IN SCHEMA catalog
    GRANT ALL PRIVILEGES ON SEQUENCES TO catalog_manager;


GRANT USAGE ON SCHEMA sales TO sales_manager;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sales TO sales_manager;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA sales TO sales_manager;
GRANT CREATE ON SCHEMA sales TO sales_manager;

-- sales_manager: права на будущие объекты

ALTER DEFAULT PRIVILEGES IN SCHEMA sales
    GRANT ALL PRIVILEGES ON TABLES TO sales_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA sales
    GRANT ALL PRIVILEGES ON SEQUENCES TO sales_manager;

-- Права для PUBLIC на catalog (чтение)

GRANT USAGE ON SCHEMA catalog TO PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA catalog TO PUBLIC;

-- PUBLIC: права на будущие объекты в catalog
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog
    GRANT SELECT ON TABLES TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA catalog
    GRANT USAGE ON SEQUENCES TO PUBLIC;