

GRANT USAGE ON SCHEMA catalog TO catalog_manager;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA catalog TO catalog_manager;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA catalog TO catalog_manager;
GRANT CREATE ON SCHEMA catalog TO catalog_manager;



GRANT USAGE ON SCHEMA sales TO sales_manager;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sales TO sales_manager;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA sales TO sales_manager;
GRANT CREATE ON SCHEMA sales TO sales_manager;


GRANT USAGE ON SCHEMA catalog TO sales_manager;
GRANT SELECT ON ALL TABLES IN SCHEMA catalog TO sales_manager;



GRANT USAGE ON SCHEMA catalog TO PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA catalog TO PUBLIC;

