
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory
    GRANT ALL PRIVILEGES ON TABLES TO inventory_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA inventory
    GRANT ALL PRIVILEGES ON SEQUENCES TO inventory_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA inventory
    GRANT SELECT ON TABLES TO worker;

ALTER DEFAULT PRIVILEGES IN SCHEMA inventory
    GRANT USAGE ON SEQUENCES TO worker;